---
mig_controller_image: quay.io/ocpmigrate/mig-controller
mig_controller_version: latest
mig_namespace: mig
mig_ui_configmap_name : mig-ui-config
mig_ui_oauth_user_scope: "user:full"
mig_ui_image: quay.io/ocpmigrate/mig-ui
mig_ui_version: latest
